### ISSUE TITLE
Support for Mobile

### ISSUE THREAD

**Issue by domoritz** [vega/roadmap#6]
Vega-Lite’s implementation of selections currently only listens to desktop interactions. In the future, Vega-Lite’s selections should also be triggered by touch events. Since mobile displays are much smaller, some of the interactions and defaults have to be adjusted. See https://github.com/vega/vega-lite/issues/4661 for details.

**Comment by domoritz** [comment]
Vega works well on mobile and Vega-Lite works except for interactions. It should be straight forward to add support if someone can spare a few days of development.

**Comment by vicatcu** [comment]
Hi! This issue has been open for a few years, and it's been about 5 months since the last post here, so I thought I would poke my head again... any updates on when this might make it into a release?

**Comment by joelostblom** [comment]
I'm moving this to Done since https://github.com/vega/vega-lite/issues/4661 was merged

**Comment by domoritz** [comment]
Yes, we recently added support for touch events in Vega and Vega-Lite.

**Comment by domoritz** [comment]
Sounds good. Thanks!

**Comment by domoritz** [comment]
Closing for now since we have basic support but this doesn't mean that we are not improving mobile support.
